"""
Mock data for RedditDemand API.
Realistic Reddit-style posts and comments about freelancer pain points.
Replace with real database queries when schema is populated.
"""

from datetime import datetime

from models import (
    Comment,
    OpportunityPost,
    SearchResultItem,
    ThreadDetail,
)


# --- Search results (10 items from r/freelance and r/entrepreneur) ---

SEARCH_RESULTS: list[SearchResultItem] = [
    SearchResultItem(
        id="abc1f2g3h",
        title="Client hasn't paid in 90 days — what do I do?",
        subreddit="freelance",
        created_utc=datetime(2023, 5, 12, 14, 22, 0),
        num_comments=47,
        activity_ratio=2.3,
        last_comment_utc=datetime(2024, 1, 8, 9, 15, 0),
        similarity_score=0.94,
        snippet="I've sent three invoices and two reminder emails. They keep saying the check is in the mail. At this point I've done $4k of work and I'm seriously considering small claims court. Has anyone actually had success with that?",
    ),
    SearchResultItem(
        id="def4j5k6l",
        title="I always forget to log my hours and then have to guess at the end of the week",
        subreddit="freelance",
        created_utc=datetime(2023, 8, 3, 11, 45, 0),
        num_comments=89,
        activity_ratio=4.1,
        last_comment_utc=datetime(2024, 2, 1, 16, 30, 0),
        similarity_score=0.87,
        snippet="Every single week I tell myself I'll track as I go. Then I get in the zone and forget. By Friday I'm trying to reconstruct 40 hours from memory and I know I'm underbilling. Lost probably $2k last year from this alone.",
    ),
    SearchResultItem(
        id="ghi7m8n9o",
        title="Scope creep is killing me — client keeps adding 'small' requests",
        subreddit="entrepreneur",
        created_utc=datetime(2022, 11, 20, 8, 10, 0),
        num_comments=156,
        activity_ratio=6.2,
        last_comment_utc=datetime(2024, 1, 28, 12, 0, 0),
        similarity_score=0.91,
        snippet="We agreed on a landing page. Now it's a landing page plus blog integration plus email capture plus three rounds of revisions. I've done 2x the original scope and they're acting like I'm being difficult for asking for more money.",
    ),
    SearchResultItem(
        id="jkl0p1q2r",
        title="Invoice software recommendations? Everything I've tried is either too expensive or a nightmare",
        subreddit="freelance",
        created_utc=datetime(2023, 2, 15, 19, 33, 0),
        num_comments=72,
        activity_ratio=3.8,
        last_comment_utc=datetime(2024, 1, 15, 10, 22, 0),
        similarity_score=0.82,
        snippet="I've tried FreshBooks, Wave, and a bunch of others. Either they want $30/month for features I don't need, or the UX is so bad I spend more time fighting the software than actually getting paid. What do solo freelancers actually use?",
    ),
    SearchResultItem(
        id="mno3s4t5u",
        title="Net 60 payment terms are destroying my cash flow",
        subreddit="entrepreneur",
        created_utc=datetime(2023, 7, 8, 16, 55, 0),
        num_comments=34,
        activity_ratio=1.9,
        last_comment_utc=datetime(2023, 12, 20, 14, 10, 0),
        similarity_score=0.88,
        snippet="Just finished a $8k project. Client has Net 60 terms. So I won't see that money until March. I have rent due in January. How do you all handle this? Do you just refuse to work with Net 60 clients?",
    ),
    SearchResultItem(
        id="pqr6v7w8x",
        title="Client wants to pay via check and mail it — is this a red flag?",
        subreddit="freelance",
        created_utc=datetime(2023, 9, 22, 9, 12, 0),
        num_comments=28,
        activity_ratio=1.2,
        last_comment_utc=datetime(2024, 1, 5, 11, 45, 0),
        similarity_score=0.76,
        snippet="They're a legit company, not a scam. But they insist on mailing checks. I'm worried about 'check is in the mail' excuses and the delay. Has anyone had good experiences with check payments from corporate clients?",
    ),
    SearchResultItem(
        id="stu9y0z1a",
        title="Manual timesheets are such a waste of time — there has to be a better way",
        subreddit="freelance",
        created_utc=datetime(2022, 4, 18, 13, 40, 0),
        num_comments=203,
        activity_ratio=8.0,
        last_comment_utc=datetime(2024, 2, 10, 8, 20, 0),
        similarity_score=0.95,
        snippet="I spend like 2 hours every week filling out timesheets for different clients. Each one has a different format. Some want Excel, some want their portal, some want a PDF. There has to be a tool that does this automatically.",
    ),
    SearchResultItem(
        id="vwx2b3c4d",
        title="How do you deal with clients who disappear for weeks then expect instant turnaround?",
        subreddit="entrepreneur",
        created_utc=datetime(2023, 10, 5, 17, 28, 0),
        num_comments=61,
        activity_ratio=2.7,
        last_comment_utc=datetime(2024, 1, 22, 9, 55, 0),
        similarity_score=0.79,
        snippet="No response for 3 weeks on the design I sent. Then suddenly 'we need this revised by tomorrow, the board meeting is Friday.' I had other clients. I'm not dropping everything because you went radio silent.",
    ),
    SearchResultItem(
        id="efg5h6i7j",
        title="Chasing payments feels like a second job",
        subreddit="freelance",
        created_utc=datetime(2023, 1, 30, 10, 5, 0),
        num_comments=94,
        activity_ratio=5.4,
        last_comment_utc=datetime(2024, 2, 5, 15, 40, 0),
        similarity_score=0.93,
        snippet="I spend more time sending 'friendly reminders' and following up than I do on some projects. One client I had to chase for 4 months. At what point do you just give up and write it off?",
    ),
    SearchResultItem(
        id="klm8k9l0m",
        title="Client changed requirements 3 times mid-project, now wants a discount",
        subreddit="entrepreneur",
        created_utc=datetime(2023, 6, 14, 14, 18, 0),
        num_comments=42,
        activity_ratio=2.1,
        last_comment_utc=datetime(2024, 1, 12, 11, 30, 0),
        similarity_score=0.85,
        snippet="We had a signed SOW. They asked for changes. I documented them and said it would add 20% to the scope. They said fine. Now at the end they're saying the final deliverable doesn't match expectations and want 15% off. I'm livid.",
    ),
]


# --- Opportunity posts (10 items, high activity_ratio 1.5–8.0) ---

OPPORTUNITY_POSTS: list[OpportunityPost] = [
    OpportunityPost(
        id="stu9y0z1a",
        title="Manual timesheets are such a waste of time — there has to be a better way",
        subreddit="freelance",
        created_utc=datetime(2022, 4, 18, 13, 40, 0),
        num_comments=203,
        activity_ratio=8.0,
        last_comment_utc=datetime(2024, 2, 10, 8, 20, 0),
        url="https://reddit.com/r/freelance/comments/stu9y0",
        ranks_on_google=True,
    ),
    OpportunityPost(
        id="ghi7m8n9o",
        title="Scope creep is killing me — client keeps adding 'small' requests",
        subreddit="entrepreneur",
        created_utc=datetime(2022, 11, 20, 8, 10, 0),
        num_comments=156,
        activity_ratio=6.2,
        last_comment_utc=datetime(2024, 1, 28, 12, 0, 0),
        url="https://reddit.com/r/entrepreneur/comments/ghi7m8",
        ranks_on_google=True,
    ),
    OpportunityPost(
        id="efg5h6i7j",
        title="Chasing payments feels like a second job",
        subreddit="freelance",
        created_utc=datetime(2023, 1, 30, 10, 5, 0),
        num_comments=94,
        activity_ratio=5.4,
        last_comment_utc=datetime(2024, 2, 5, 15, 40, 0),
        url="https://reddit.com/r/freelance/comments/efg5h6",
        ranks_on_google=False,
    ),
    OpportunityPost(
        id="def4j5k6l",
        title="I always forget to log my hours and then have to guess at the end of the week",
        subreddit="freelance",
        created_utc=datetime(2023, 8, 3, 11, 45, 0),
        num_comments=89,
        activity_ratio=4.1,
        last_comment_utc=datetime(2024, 2, 1, 16, 30, 0),
        url="https://reddit.com/r/freelance/comments/def4j5",
        ranks_on_google=False,
    ),
    OpportunityPost(
        id="jkl0p1q2r",
        title="Invoice software recommendations? Everything I've tried is either too expensive or a nightmare",
        subreddit="freelance",
        created_utc=datetime(2023, 2, 15, 19, 33, 0),
        num_comments=72,
        activity_ratio=3.8,
        last_comment_utc=datetime(2024, 1, 15, 10, 22, 0),
        url="https://reddit.com/r/freelance/comments/jkl0p1",
        ranks_on_google=False,
    ),
    OpportunityPost(
        id="vwx2b3c4d",
        title="How do you deal with clients who disappear for weeks then expect instant turnaround?",
        subreddit="entrepreneur",
        created_utc=datetime(2023, 10, 5, 17, 28, 0),
        num_comments=61,
        activity_ratio=2.7,
        last_comment_utc=datetime(2024, 1, 22, 9, 55, 0),
        url="https://reddit.com/r/entrepreneur/comments/vwx2b3",
        ranks_on_google=False,
    ),
    OpportunityPost(
        id="abc1f2g3h",
        title="Client hasn't paid in 90 days — what do I do?",
        subreddit="freelance",
        created_utc=datetime(2023, 5, 12, 14, 22, 0),
        num_comments=47,
        activity_ratio=2.3,
        last_comment_utc=datetime(2024, 1, 8, 9, 15, 0),
        url="https://reddit.com/r/freelance/comments/abc1f2",
        ranks_on_google=False,
    ),
    OpportunityPost(
        id="klm8k9l0m",
        title="Client changed requirements 3 times mid-project, now wants a discount",
        subreddit="entrepreneur",
        created_utc=datetime(2023, 6, 14, 14, 18, 0),
        num_comments=42,
        activity_ratio=2.1,
        last_comment_utc=datetime(2024, 1, 12, 11, 30, 0),
        url="https://reddit.com/r/entrepreneur/comments/klm8k9",
        ranks_on_google=False,
    ),
    OpportunityPost(
        id="mno3s4t5u",
        title="Net 60 payment terms are destroying my cash flow",
        subreddit="entrepreneur",
        created_utc=datetime(2023, 7, 8, 16, 55, 0),
        num_comments=34,
        activity_ratio=1.9,
        last_comment_utc=datetime(2023, 12, 20, 14, 10, 0),
        url="https://reddit.com/r/entrepreneur/comments/mno3s4",
        ranks_on_google=False,
    ),
    OpportunityPost(
        id="nop4u5v6w",
        title="What contract template do you use for freelance work?",
        subreddit="freelance",
        created_utc=datetime(2021, 3, 10, 9, 0, 0),
        num_comments=312,
        activity_ratio=1.8,
        last_comment_utc=datetime(2024, 2, 8, 14, 5, 0),
        url="https://reddit.com/r/freelance/comments/nop4u5",
        ranks_on_google=True,
    ),
]


# --- Single thread with 8 comments (hierarchical) ---

MOCK_THREAD_ID = "mock_thread_001"

THREAD_DETAIL: ThreadDetail = ThreadDetail(
    id=MOCK_THREAD_ID,
    subreddit="freelance",
    title="Client hasn't paid in 90 days — what do I do?",
    body="I delivered the project in November. Sent the invoice same day. It's now February and I've heard nothing but 'we're processing it' for the last 6 weeks. The amount is $4,200. Do I send a formal demand letter? Small claims? I'm in CA, they're in NY.",
    author="frustrated_freelancer_99",
    created_utc=datetime(2023, 11, 15, 16, 30, 0),
    score=127,
    url="https://reddit.com/r/freelance/comments/mock_thread_001",
    num_comments=47,
    last_comment_utc=datetime(2024, 1, 8, 9, 15, 0),
    recent_comment_count=12,
    activity_ratio=2.3,
    reconstructed_text="Client hasn't paid in 90 days — what do I do?\n\nI delivered the project in November. Sent the invoice same day. It's now February and I've heard nothing but 'we're processing it' for the last 6 weeks. The amount is $4,200. Do I send a formal demand letter? Small claims? I'm in CA, they're in NY.\n\n[Top comment] I've been through this. Send a certified demand letter giving them 10 days. If no response, file in small claims. The threat of a judgment on their record often gets them to pay before the hearing.\n\n[Reply] Did you use a lawyer for the demand letter or just wrote it yourself?\n\n[Reply to reply] I wrote it myself. Plenty of templates online. Key is to be professional, state the amount, give a deadline, and say you'll pursue legal action. Worked for me.",
    comments=[
        Comment(
            id="c001",
            post_id=MOCK_THREAD_ID,
            parent_id=MOCK_THREAD_ID,
            parent_type="post",
            author="legal_eagle_freelance",
            body="I've been through this. Send a certified demand letter giving them 10 days to pay. If no response, file in small claims. The threat of a judgment on their record often gets them to pay before the hearing.",
            created_utc=datetime(2023, 11, 15, 18, 45, 0),
            score=89,
            controversiality=0,
        ),
        Comment(
            id="c002",
            post_id=MOCK_THREAD_ID,
            parent_id="c001",
            parent_type="comment",
            author="frustrated_freelancer_99",
            body="Did you use a lawyer for the demand letter or just wrote it yourself?",
            created_utc=datetime(2023, 11, 15, 19, 12, 0),
            score=34,
            controversiality=0,
        ),
        Comment(
            id="c003",
            post_id=MOCK_THREAD_ID,
            parent_id="c001",
            parent_type="comment",
            author="legal_eagle_freelance",
            body="I wrote it myself. Plenty of templates online. Key is to be professional, state the amount, give a deadline, and say you'll pursue legal action. Worked for me.",
            created_utc=datetime(2023, 11, 15, 19, 28, 0),
            score=56,
            controversiality=0,
        ),
        Comment(
            id="c004",
            post_id=MOCK_THREAD_ID,
            parent_id="c001",
            parent_type="comment",
            author="invoice_warrior",
            body="Seconding this. I waited 4 months being 'nice' about it. The day I sent the demand letter they suddenly found the check. Coincidence? I think not.",
            created_utc=datetime(2023, 11, 16, 8, 5, 0),
            score=42,
            controversiality=0,
        ),
        Comment(
            id="c005",
            post_id=MOCK_THREAD_ID,
            parent_id=MOCK_THREAD_ID,
            parent_type="post",
            author="net30_advocate",
            body="Going forward, add late payment fees to your contract. 1.5% per month after 30 days. It's standard and it makes clients prioritize your invoice.",
            created_utc=datetime(2023, 11, 15, 20, 0, 0),
            score=67,
            controversiality=1,
        ),
        Comment(
            id="c006",
            post_id=MOCK_THREAD_ID,
            parent_id="c005",
            parent_type="comment",
            author="new_to_freelance",
            body="Do clients actually agree to that? I feel like they'd just go with someone who doesn't have that clause.",
            created_utc=datetime(2023, 11, 15, 21, 15, 0),
            score=12,
            controversiality=0,
        ),
        Comment(
            id="c007",
            post_id=MOCK_THREAD_ID,
            parent_id="c005",
            parent_type="comment",
            author="net30_advocate",
            body="The good ones do. The ones who push back are often the ones who pay late. It's a filter.",
            created_utc=datetime(2023, 11, 15, 21, 45, 0),
            score=38,
            controversiality=0,
        ),
        Comment(
            id="c008",
            post_id=MOCK_THREAD_ID,
            parent_id="c004",
            parent_type="comment",
            author="frustrated_freelancer_99",
            body="That's encouraging. I'll draft one this week. Thanks everyone.",
            created_utc=datetime(2023, 11, 16, 10, 30, 0),
            score=15,
            controversiality=0,
        ),
    ],
)
